### ISSUE TITLE
Prerequisites of Local Environment are missing in README

### ISSUE THREAD

**Issue by jianingwang123** [Azure-Samples/llama-index-javascript#10]
**Describe the issue:**

In the local environment , it need to install and open `Docker`, but the Prerequisites in [README](https://github.com/Azure-Samples/llama-index-javascript#prerequisites) are not specified.

![image](https://github.com/Azure-Samples/llama-index-javascript/assets/141212663/3ee5849c-9a0d-4d04-ad31-0fa66c8033e2)

**Suggestion:**

Add `Docker` into the Prerequisites in README.

@hemarina and @manekinekko for notification.

**Comment by manekinekko** [comment]
Fixed by #11
