### ISSUE TITLE
Fail to run `azd up` by using Codespaces and Dev Containers

### ISSUE THREAD

**Issue by jianingwang123** [Azure-Samples/llama-index-javascript#7]
**Describe the issue:**
When running the `azd up` command in `Codespaces` or `Dev Containers` , the following error appears:
( `azd` is missing from the two environments, the following are the results running after we manually installed `azd` )
- Codespaces
![image](https://github.com/Azure-Samples/llama-index-javascript/assets/141212663/c3afb68c-8e4e-4c09-98dd-4384bce64642)
- Dev Containers
![image](https://github.com/Azure-Samples/llama-index-javascript/assets/141212663/d81bf300-7b99-48b5-bd4d-65db257dadff)

**Repro Steps:**

1.Open the template by using GitHub Codespaces or VS Code Dev Containers.
2.Run `azd auth login --use-device-code` or `azd auth login`
3.Run `azd up`

**Environment:**

- azd version: `1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)`
- OS: GitHub Codespaces and VS Code Dev Containers.

**Expected behavior:**

Successfully run `azd up` .

@hemarina and @manekinekko for notification.

**Comment by manekinekko** [comment]
Fixed by #11
