### ISSUE TITLE
Fail to run the application locally after "npm run dev"

### ISSUE THREAD

**Issue by jianingwang123** [Azure-Samples/llama-index-javascript#8]
**Describe the issue:**

After running the `npm run dev` command locally and open the URL `http://localhost:3000` , when send a message , the following error appears:
![image](https://github.com/Azure-Samples/llama-index-javascript/assets/141212663/b3d3d77c-05fd-4526-a0ac-2e098959cc38)
![image](https://github.com/Azure-Samples/llama-index-javascript/assets/141212663/d7241e0e-7e7d-4c2a-9c26-70fb25048950)

**Repro Steps:**

1.Run `azd init --template llama-index-javascript`
2.Run `azd auth login`
3.Run `npm install`
4.Run `azd up`
5.Run `npm run dev`
6.Open the URL `http://localhost:3000` and send a message.

**Environment:**

- azd version: `1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)`
- OS:  Windows11
- Nodejs version: `v20.9.0`

**Expected behavior:**

The application can operate normally.

@hemarina and @manekinekko for notification.

**Comment by manekinekko** [comment]
Fixed by #11
