### ISSUE TITLE
Fail to run the command `azd pipeline config`

### ISSUE THREAD

**Issue by jianingwang123** [Azure-Samples/llama-index-javascript#9]
**Describe the issue:**

When running the command `azd pipeline config` , the following error appears: 
![image](https://github.com/Azure-Samples/llama-index-javascript/assets/141212663/d9148c31-42d2-4a3e-b0ea-0855d4d4cf76)

![image](https://github.com/Azure-Samples/llama-index-javascript/assets/141212663/bb7a0711-1658-4ed5-8b99-186be6dcbb81)

**Repro Steps:**

1.Run `azd init --template llama-index-javascript`
2. Run `azd auth login`
3. Run `npm install`
4. Run `azd up`
5. Run `azd pipeline config`

**Environment:**

- azd version: `1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)`
- OS: Windows11

**Expected behavior:**

Run `azd pipeline config` succesfully.

@hemarina and @manekinekko for notification.

**Comment by manekinekko** [comment]
Thank you @jianingwang123 Will fix it and report back.

**Comment by manekinekko** [comment]
Hi @jianingwang123 I fixed the issue. https://github.com/Azure-Samples/llama-index-javascript/actions/runs/9957204618/job/27509469889

**Comment by jianingwang123** [comment]
@manekinekko 
When executing `azd pipeline config`, we will encounter error: `repo *** not found`. See the picture for detailed error.
Besides, when we try to set the repository to public, it passes after re-running. This is strange. 
Is this template missing any configuration or permissions?

![image](https://github.com/user-attachments/assets/4c9c804d-564e-462b-b9f3-fa870dfe2519)

**Comment by manekinekko** [comment]
Can you describe the flow for `azd pipeline config`? When I run this command this is the output I get. Is there something missing?
![image](https://github.com/user-attachments/assets/7599835c-1339-443b-891b-a7e674133132)

**Comment by jianingwang123** [comment]
Please create a new private repository instead of an existing public repository . This is the output I get : 

![image](https://github.com/user-attachments/assets/617e4d7d-41c1-41c0-9d6f-3e597473a9b4)

**Comment by manekinekko** [comment]
Hi @jianingwang123 my understanding is that the `azd pipeline config` should run succefully for the main official repo, not private forks. Is that correct? cc @anfibiacreativa

**Comment by manekinekko** [comment]
Hi @jianingwang123 I just double checked, the issue is happening because the project is private, when you switch to public, the pipeline is validated. https://github.com/manekinekko/azd-tmpl/actions/runs/9974814966/job/27563498249

**Comment by v-xuto** [comment]
@manekinekko For azd template testing, when running `azd pipeline config`, it is expected that both public and private repositories will succeed. For example, https://github.com/Azure-Samples/todo-nodejs-mongo, this template will work even for private repos. Also, not everyone has access to public repos.

**Comment by manekinekko** [comment]
@v-xuto thank you for the clarifications. Could you please guide me on how I can set this correctly?

**Comment by v-xuto** [comment]
> @v-xuto thank you for the clarifications. Could you please guide me on how I can set this correctly?

@manekinekko This template triggered three GitHub Actions pipelines: `Deploy to Azure`, `Build and test`, and `Validate AZD template`. Both `Deploy to Azure` and `Build and test`, passed successfully, while `Validate AZD template` encountered a permission issue. After investigation and analysis, by removing two lines of code from file [validate-infra.yaml](https://github.com/Azure-Samples/llama-index-javascript/blob/main/.github/workflows/validate-infra.yaml#L16) and then executing `azd pipeline config`, the result was PASS. You can have a try.

- Remove two lines of code from file [validate-infra.yaml](https://github.com/Azure-Samples/llama-index-javascript/blob/main/.github/workflows/validate-infra.yaml#L16):

![image](https://github.com/user-attachments/assets/21c5d2a5-aa52-4c33-8226-54df99e2858b)

- Github pipeline result:

![image](https://github.com/user-attachments/assets/5a6dc2d2-2738-45ee-a035-89ca7cfa5a9f)

**Comment by manekinekko** [comment]
Thank you @v-xuto I applied the fix. Would you like to try again please?

**Comment by v-xuto** [comment]
> Thank you @v-xuto I applied the fix. Would you like to try again please?

We have verified, this issue has been fixed.
